app:
  block:
    threshold: 5
  storage:
    strategy: IN_MEMORY  # IN_MEMORY, в дальнейшем попробовать другие варианты

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  liquibase:
    enabled: true
    change-log: classpath:/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #Для работы без сертификатов
  kafka:
    bootstrap-servers: localhost:9093
    properties:
      security:
        protocol: PLAINTEXT
    topics:
      cdc-topic: postgres-server.public.users
      output-topic-tumbling: user-activity-stats-tumbling
      output-topic-hopping: user-activity-stats-hopping
      output-topic-session: user-activity-stats-session

    streams:
      application-id: user-activity-streams
      auto-startup: true
      properties:
        default:
          key:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value:
            serde: org.springframework.kafka.support.serializer.JsonSerde

#Разкомментировать для работы с SSL
#  kafka:
#    bootstrap-servers: localhost:9093
#    properties:
#      security:
#        protocol: SSL
#      ssl:
#        # Для самоподписанного сертификата отключаем проверку hostname
#        endpoint:
#          identification:
#            algorithm: ""
#        # Пути к сертификатам укажите свой путь
#        trust-store-location: C:\Users\54421\IdeaProjects\user-activity-monitoring\docker\ssl\truststore.jks
#        trust-store-password: changeit
#        key-store-location: C:\Users\54421\IdeaProjects\user-activity-monitoring\docker\ssl\kafka.jks
#        key-store-password: changeit
#        key-password: changeit
#        # Явно указываем протокол
#        protocol: TLSv1.2
#        enabled-protocols: TLSv1.2
#    topics:
#      cdc-topic: postgres-server.public.users
#      output-topic-tumbling: user-activity-stats-tumbling
#      output-topic-hopping: user-activity-stats-hopping
#      output-topic-session: user-activity-stats-session
#    streams:
#      application-id: user-activity-streams
#      auto-startup: true
#      properties:
#        default:
#          key:
#            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#          value:
#            serde: org.springframework.kafka.support.serializer.JsonSerde
#        # Дополнительные настройки для SSL в Streams
#        security:
#          protocol: SSL
#        ssl:
#          truststore:
#            location: C:\Users\54421\IdeaProjects\user-activity-monitoring\docker\ssl\truststore.jks
#            password: changeit
#          keystore:
#            location: C:\Users\54421\IdeaProjects\user-activity-monitoring\docker\ssl\kafka.jks
#            password: changeit
#          key:
#            password: changeit
#          endpoint:
#            identification:
#              algorithm: ""


debezium:
  host: http://localhost:8083/connectors/
  name: postgres-connector
  database:
    hostname: localhost
    port: 5432
    user: user
    password: password
    dbname: userdb
    schema: public
  topic-prefix: postgres-server

server:
  port: 8080

logging:
  level:
    com.user.activity.monitoring: DEBUG
    org.apache.kafka: INFO
    io.debezium: DEBUG
    org.springframework.kafka: INFO
    liquibase: DEBUG
    root: INFO
    #sun.security.ssl: DEBUG

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "health,info,metrics,prometheus"